name: collaction_app
description: The CollAction app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  bloc: ^8.0.2
  cached_network_image: ^3.2.0
  country_codes: ^2.1.1
  country_icons: ^2.0.2
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  dots_indicator: ^2.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  expandable_page_view: ^1.0.10
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  firebase_remote_config: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  http: ^0.13.4
  image: ^3.1.1
  image_cropper: ^2.0.3
  image_picker: ^0.8.4+7
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  mime: ^1.0.2
  mocktail: ^0.3.0
  package_info_plus: ^1.3.0
  phone_number: ^0.12.0+2
  rive: ^0.9.0
  rxdart: ^0.27.3
  share_plus: ^4.0.10
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  url_launcher: ^6.0.18
  webview_flutter: ^3.0.0

dev_dependencies:
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  firebase_auth_mocks: ^0.8.2
  flutter_launcher_icons: ^0.9.2
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.3
  lint: ^1.8.2
  mockito: ^5.0.17
  network_image_mock: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.png"
  adaptive_icon_foreground: "assets/images/icons/app_icon.png"
  adaptive_icon_background: "#ff2eb394"
  remove_alpha_ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/vectors/
  fonts:
    - family: CollactionIcons
      fonts:
        - asset: assets/fonts/icons/CollactionIcons.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
