name: collaction_app
description: The CollAction app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  country_codes: ^2.2.0
  country_icons: ^2.0.2
  dartz: ^0.10.1
  dots_indicator: ^2.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  expandable_page_view: ^1.0.10
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  http: ^0.13.5
  image: ^3.2.2
  image_cropper: ^3.0.0
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  ionicons: ^0.2.1
  json_annotation: ^4.7.0
  mocktail: ^0.3.0
  package_info_plus: ^3.0.0
  phone_number: ^1.0.0
  rive: ^0.9.1
  rxdart: ^0.27.5
  share_plus: ^6.0.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.6
  webview_flutter: ^3.0.4

dev_dependencies:
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  firebase_auth_mocks: ^0.8.6
  flutter_launcher_icons: ^0.10.0
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.3
  lint: ^1.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.png"
  adaptive_icon_foreground: "assets/images/icons/app_icon.png"
  adaptive_icon_background: "#ff2eb394"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/vectors/

  fonts:
    - family: CollactionIcons
      fonts:
        - asset: assets/fonts/icons/CollactionIcons.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
